### ISSUE TITLE
Update from 2.0 to 2.1.1 from UI hanging

### ISSUE THREAD

**Issue by morphias2004** [UnchartedBull/OctoDash#1126]
Running Octodash v2.0. on a Pi4 4Gb with Octoprint 1.4.2, OctoPi 0.17.0 and Python 3.7.3 with a HyperPixel 4.0.

UI notified of an update to 2.1.1 was available. I confirmed the update and it went to a progress bar that says "Installing update" and "This may take a while".

20mins later and it's still sitting there with this message. :(

**Comment by morphias2004** [comment]
I've worked around this by hard power cycling the Pi and running the update script from the Pi command line.

**Comment by thegarbz** [comment]
@morphias2004 This is addressed in the wiki and the release notes for 2.1.0. You need to add a script to get updates working, in the future. https://github.com/UnchartedBull/OctoDash/wiki/Update#in-app-update

@UnchartedBull given these releases came so close to each other it may be worth putting it in the release notes for 2.1.1 as well.

**Comment by ruralaccent** [comment]
My in app update isn't hanging, but it's taking almost 50 minutes to download. When I update my other Octoprint on another Pi via Putty, it takes only a couple of minutes.

**Comment by carl1961** [comment]
Update was same as @morphias2004 , doing wiki failed, because I had no script folder. I got all that fixed and got the Octodash to update, but update seems broke.  " Can't get Octoprint script!"  this is how I got the update script installed and working.


**Making Octodash update from OctoDash**

I did not have a scripts folder so i had to make one

Log in to pi  with putty (or whatever terminal you choose)

  ******   Creating  scripts  directory  ******   

  mkdir scripts 

***** creating script  ~/scripts/update-octodash   ******

sudo nano ~/scripts/update-octodash

**** add this  ****

#!/bin/bash

dpkg -i /tmp/octodash.deb
rm /tmp/octodash.deb


****save and exit nano  Ctrl o  Ctrl x ******

*** Make the script executable:


sudo chmod +x ~/scripts/update-octodash

****** Enable passwordless sudo for the update script (/etc/sudoers.d/update-octodash): ****
**** I did not have file , so this is new file too*****

sudo nano /etc/sudoers.d/update-octodash

****** add this ****

pi ALL=NOPASSWD: /home/pi/scripts/update-octodash

****save and exit nano  Ctrl o enter Ctrl x ******

***** Then reboot pi *******

sudo reboot

![IMG_20201025_075049](https://user-images.githubusercontent.com/3056821/97108370-32071900-169b-11eb-9307-47f6f115fad2.jpg)
![IMG_20201025_075102](https://user-images.githubusercontent.com/3056821/97108373-34697300-169b-11eb-95d8-c727c6f99f64.jpg)
![IMG_20201025_075107](https://user-images.githubusercontent.com/3056821/97108376-359aa000-169b-11eb-9b8d-161d03cfe6b9.jpg)
![IMG_20201025_075119](https://user-images.githubusercontent.com/3056821/97108377-36cbcd00-169b-11eb-858d-2f282253044c.jpg)
![IMG_20201025_075130](https://user-images.githubusercontent.com/3056821/97108379-38959080-169b-11eb-8adf-376e219fe180.jpg)
![IMG_20201025_075155](https://user-images.githubusercontent.com/3056821/97108380-39c6bd80-169b-11eb-8252-019c074d9f1f.jpg)
![IMG_20201025_081205](https://user-images.githubusercontent.com/3056821/97108382-3af7ea80-169b-11eb-8327-a3961bf737f9.jpg)

**Comment by carl1961** [comment]
@ruralaccent  that would be most like your wifi speed, mine download less that a minute

**Comment by carl1961** [comment]
I even tried adding the delay as once mentioned before , but still not working, " Can't get octoPrint script"
delay worked, as i could see the delay after ratpoison 
********************************
Edit:  UnchartedBull

By how long are you delaying the start? 
Best way to delay the OctoDash start is probably by adding a sleep <seconds> to ~/cd..
.
********************************
***********login as root and not pi ********************

nano /home/pi/.xinitrc

***** add sleep 20 above octodash **********
sleep 20

****save and exit nano  Ctrl o enter Ctrl x ******

***** Then reboot pi *******

sudo reboot

**Comment by carl1961** [comment]
even manually updating from Unofficial OctoDash Builds  still "can't get OctoPrint script!"

![install](https://user-images.githubusercontent.com/3056821/97111611-d1350c00-16ad-11eb-902b-1193c866a5e6.PNG)
![install2](https://user-images.githubusercontent.com/3056821/97111612-d1350c00-16ad-11eb-87fe-67ea64eae280.PNG)
![install3](https://user-images.githubusercontent.com/3056821/97111613-d1350c00-16ad-11eb-80f6-b8f741ea32bc.PNG)

**Comment by UnchartedBull** [comment]
Is your printer connected to OctoPrint?

**Comment by carl1961** [comment]
**BackDated to 2.0.0 and running again**
removing octodash

sudo apt-get  remove octodash
*********************************
**Download the latest release Check for newer version and replace v2.0.0 with the latest version (Releases)**
*********************************
wget -O octodash.deb https://github.com/UnchartedBull/OctoDash/releases/download/v2.0.0/octodash_2.0.0_armv7l.deb
*********************************
**Install the app**
*********************************
sudo dpkg -i octodash.deb

![IMG_20201025_105915](https://user-images.githubusercontent.com/3056821/97112407-19562d80-16b2-11eb-910a-5ec26fc035a9.jpg)
![IMG_20201025_105939](https://user-images.githubusercontent.com/3056821/97112410-1c511e00-16b2-11eb-82d8-13a9742f60df.jpg)
********************************
 Then reboot pi 
********************************
sudo reboot

**Comment by carl1961** [comment]
@UnchartedBull  if your referring to me, I just redid update again after reinstalling 2.0 as above post and 2.1.1 works, but this time I made sure octoprint was up in the web browse.

**Comment by thegarbz** [comment]
@carl1961 I too saw the script error, but after following the instructions (restarting) I haven't seen it since.

**Comment by UnchartedBull** [comment]
ok seems like everything is working for everyone now. Closing this here, if you still experience issues please comment / reopen.

@thegarbz good idea, updated the release notes for 2.1.1.
