### ISSUE TITLE
OctoPrint 1.5 (final) still doesn't show sub-folder content

### ISSUE THREAD

**Issue by zdm-as** [UnchartedBull/OctoDash#1184]
I installed octodash and all the corresponding octoprint 3rdparty plugins yesterday. Installation and setup went smooth. The problem is that I can't access a single gcode file - always comes up with "cant't retrieve folders ..." error msg. -> see screenshots. 

All the other menu items just works as expected. I can (or have to) upload and access my gcode files via octoprint web interface (or via the OctoPod app) and when the print is running the current file is correctly shown at the octodash screen (percentage, print time, layer progress, even the Prusa thumbnail preview) - everything except the access/load file menu works fine :)

OctoDash 2.1.1
OctoPrin 1.5rc
RaspberryPi 4B
SanDisk SD card 64GB (only a few folders & files on the medium - not hundreds ...)

![IMG_7807](https://user-images.githubusercontent.com/74570344/99316690-112e7f80-2865-11eb-83e3-63b4442b742c.JPG)
![IMG_7808](https://user-images.githubusercontent.com/74570344/99316700-1390d980-2865-11eb-8728-9f36e0c0d8c1.JPG)

**Comment by UnchartedBull** [comment]
I see that you're running 1.5rc. Which rc exactly are you using? There was an error in rc1 which was fixed in rc2 according to the release notes:

![Screenshot 2020-11-18 at 17 37 38](https://user-images.githubusercontent.com/19818061/99559295-e9562d80-29c4-11eb-8048-3366daaf696d.png)

Please upgrade to 1.5rc2 and check whether the error still occurs.

**Comment by zdm-as** [comment]
You're absolutely right. At the time of writing rc1 was the latest release. I've now installed the rc3 (just released today) and also updated OctoDash to the most recent v 2.1.2. So the api access problem is gone but now only the files in the root folder are listed  - all sub-folders shows empty (0 files).  Probably another rc-related problem (yet still a remarkable improvement ;) ...

**Comment by UnchartedBull** [comment]
I'll check what might have changed with the API or whether that is a bug in the RC :)

**Comment by zdm-as** [comment]
@UnchartedBull just fyi I already updated to the 1.5 final release but the sub-folder problem still persists.

**Comment by seipekm** [comment]
@UnchartedBull i can confirm

**Comment by Kawuezel** [comment]
@UnchartedBull Yes, same here. No files in folders on OctoPrint 1.5

**Comment by UnchartedBull** [comment]
I'll have a look at this and publish a patch release today or tomorrow if it's an issue with OctoDash :)

**Comment by UnchartedBull** [comment]
Quick update: This seems to be an issue with OctoPrint, rather than OctoDash (at least from what I can tell right now). I opened an issue over in their repository: https://github.com/OctoPrint/OctoPrint/issues/3844. I'll keep this issue open and pin it until this get's resolved (either via OctoDash or OctoPrint, whichever turns out to be the culprit of this)

**Comment by UnchartedBull** [comment]
Confirmed bug in OctoPrint. Please have a look at the linked issue for me details (and a possible release date, which could be a while according to foosel)

**Comment by Kawuezel** [comment]
Thanks for your help and update @UnchartedBull. So we will have to wait or not use subfolders until this has been fixed.

**Comment by seipekm** [comment]
I test now thenew octoprint Version 1.5.1. Subitems are here but the folder counter is 0

**Comment by UnchartedBull** [comment]
Ok that is great news! The folder count should be fixed (or removed depending whether it's still feasible) in the next release :)
